[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Redirige toutes les routes vers index.html (SPA-like)
[[redirects]]
  from = "/historique"
  to = "/historique.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
